backend/controllers/BillController.php
<?php

namespace backend\controllers;

use common\components\BillingAction;
use common\models\Bill;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use Yii;

class BillController extends \yii\web\Controller
{
	/**
	 * @return array
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['create', 'delete', 'update', 'list-by-client', 'view', 'all-list'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}

	/**
	 * @param integer $clientId
	 *
	 * @return string
	 */
    public function actionListByClient($clientId)
    {
    	$query = Bill::find()->where(['client_id' => $clientId]);
    	$dataProvider = new ActiveDataProvider(['query' => $query]);

        return $this->render('index', ['dataProvider' => $dataProvider, 'clientId' => $clientId]);
    }

	public function actionAllList()
	{
		$query = Bill::find()->joinWith(['client']);
		$dataProvider = new ActiveDataProvider(['query' => $query]);

		return $this->render('index', ['dataProvider' => $dataProvider, 'clientId' => false]);
    }

	/**
	 * @param $clientId
	 *
	 * @return string
	 * @throws \Exception
	 */
	public function actionCreate($clientId)
	{
		$bill = new Bill(['client_id' => $clientId]);
		if ($bill->load(Yii::$app->request->post()) && $bill->save() && BillingAction::changeBill($bill)) {
			$this->redirect(['bill/list-by-client', 'clientId' => $clientId]);
		}

		return $this->render('create', ['model' => $bill]);
    }

	/**
	 * @param $id
	 *
	 * @return string
	 * @throws \Exception
	 */
	public function actionUpdate($id)
	{
		$bill = $this->findModel($id);

		if ($bill->load(Yii::$app->request->post()) && $bill->save() && BillingAction::changeBill($bill)) {
			$this->redirect(['bill/list-by-client', 'clientId' => $bill->client_id]);
		}

		return $this->render('update', ['model' => $bill]);
    }

	/**
	 * @param $id
	 *
	 * @return array|Bill|null|\yii\db\ActiveRecord
	 */
    private function findModel($id)
    {
	    if (!($model = Bill::find()->byPk($id)->one())) {
		    throw new NotFoundHttpException('Указанная страница не найдена.');
	    }

	    return $model;
    }
}

backend/controllers/CostController.php
<?php

namespace backend\controllers;

use common\components\BillingAction;
use common\models\Cost;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use Yii;

class CostController extends \yii\web\Controller
{
	/**
	 * @return array
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['list-by-client', 'create', 'delete', 'update', 'view', 'all-list'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}

	/**
	 * @param integer $clientId
	 *
	 * @return string
	 */
	public function actionListByClient($clientId)
	{
		$query = Cost::find()->where(['client_id' => $clientId]);
		$dataProvider = new ActiveDataProvider(['query' => $query]);

		return $this->render('index', ['dataProvider' => $dataProvider, 'clientId' => $clientId]);
	}

	/**
	 * @return string
	 */
	public function actionAllList()
	{
		$query = Cost::find()->joinWith(['client']);
		$dataProvider = new ActiveDataProvider(['query' => $query]);

		return $this->render('index', ['dataProvider' => $dataProvider, 'clientId' => false]);
	}

	/**
	 * @param $clientId
	 *
	 * @return string
	 * @throws \Exception
	 * @throws \yii\db\Exception
	 */
	public function actionCreate($clientId)
	{
		$cost = new Cost(['client_id' => $clientId]);
		if ($cost->load(Yii::$app->request->post()) && $cost->save() && BillingAction::changeCost($cost)) {
			$this->redirect(['cost/list-by-client', 'clientId' => $clientId]);
		}

		return $this->render('create', ['model' => $cost]);
	}

	/**
	 * @param $id
	 *
	 * @return string
	 * @throws \Exception
	 * @throws \yii\db\Exception
	 */
	public function actionUpdate($id)
	{
		$cost = $this->findModel($id);

		if ($cost->load(Yii::$app->request->post()) && $cost->save() && BillingAction::changeCost($cost)) {
			$this->redirect(['cost/list-by-client', 'clientId' => $cost->client_id]);
		}

		return $this->render('update', ['model' => $cost]);
	}

	/**
	 * @param $id
	 *
	 * @return bool
	 * @throws \Exception
	 * @throws \Throwable
	 * @throws \yii\db\StaleObjectException
	 */
	public function actionDelete($id)
	{
		$cost = $this->findModel($id);
		$clientId = $cost->client_id;
		if ($cost->delete()) {
			$this->redirect(['cost/list-by-client', 'clientId' => $clientId]);
		}

		return false;
	}

	/**
	 * @param $id
	 *
	 * @return array|Cost|null|\yii\db\ActiveRecord
	 */
	private function findModel($id)
	{
		if (!($model = Cost::find()->where(['id' => $id])->one())) {
			throw new NotFoundHttpException('Указанная страница не найдена.');
		}

		return $model;
	}

}

backend/views/layouts/main.php
<?

/* @var $this \yii\web\View */
/* @var $content string */

use backend\assets\AppAsset;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use common\widgets\Alert;

AppAsset::register($this);
?>
<? $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <? $this->head() ?>
</head>
<body>
<? $this->beginBody() ?>

<div class="wrap">
    <?
    NavBar::begin([
        'brandLabel' => Yii::$app->name,
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    $menuItems = [
        ['label' => 'Home', 'url' => ['/site/index']],
    ];
    if (Yii::$app->user->isGuest) {
        $menuItems[] = ['label' => 'Login', 'url' => ['/site/login']];
    } else {
	    $menuItems[] = ['label' => 'Клиенты', 'url' => ['/user/index']];
	    $menuItems[] = ['label' => 'Платежи', 'url' => ['/bill/all-list']];
	    $menuItems[] = ['label' => 'Расходы', 'url' => ['/cost/all-list']];
	    $menuItems[] = '<li>'
            . Html::beginForm(['/site/logout'], 'post')
            . Html::submitButton(
                'Logout (' . Yii::$app->user->identity->login . ')',
                ['class' => 'btn btn-link logout']
            )
            . Html::endForm()
            . '</li>';
    }
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => $menuItems,
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= Alert::widget() ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; <?= Html::encode(Yii::$app->name) ?> <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<? $this->endBody() ?>
</body>
</html>
<? $this->endPage() ?>