common/models/Cost.php
<?php

namespace common\models;

use yii\db\ActiveRecord;
use yii\behaviors\AttributeBehavior;

/**
 * This is the model class for table "cost".
 *
 * @property int $id
 * @property int $client_id
 * @property string $date_from
 * @property string $date_to
 * @property string $sum
 *
 * @property User $client
 * @property Bill[] $bills
 */
class Cost extends ActiveRecord
{
	const EVENT_CHANGE_COST = 'change_in_cost';

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cost';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['client_id'], 'integer'],
            [['date_from', 'date_to'], 'safe'],
            [['sum'], 'number'],
            [['client_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['client_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'client_id' => 'Client ID',
            'date_from' => 'Date From',
            'date_to' => 'Date To',
            'sum' => 'Sum',
        ];
    }

	/**
	 * @return array
	 */
	public function behaviors()
	{
		return [
			[
				'class' => AttributeBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => ['date_from'],
					ActiveRecord::EVENT_BEFORE_UPDATE => ['date_from'],
				],
				'value' => function ($event) {
					return date('Y-m-d', strtotime($this->date_from));
				},
			],
			[
				'class' => AttributeBehavior::className(),
				'attributes' => [
					ActiveRecord::EVENT_BEFORE_INSERT => ['date_to'],
					ActiveRecord::EVENT_BEFORE_UPDATE => ['date_to'],
				],
				'value' => function ($event) {
					return date('Y-m-d', strtotime($this->date_to));
				},
			]
		];
	}

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClient()
    {
        return $this->hasOne(User::className(), ['id' => 'client_id']);
    }

	/**
	 * @return \yii\db\ActiveQuery
	 */
	public function getBills()
	{
		return $this->hasMany(Bill::class, ['client_id' => 'client_id'])->inverseOf('cost');
	}

    /**
     * @inheritdoc
     * @return CostQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CostQuery(get_called_class());
    }
}

backend/controllers/CostController.php
<?php

namespace backend\controllers;

use common\components\BillingAction;
use common\models\Cost;
use yii\data\ActiveDataProvider;
use yii\filters\AccessControl;
use Yii;

class CostController extends \yii\web\Controller
{
	/**
	 * @return array
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['list-by-client', 'create', 'delete', 'update', 'view', 'all-list'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}

	/**
	 * @param integer $clientId
	 *
	 * @return string
	 */
	public function actionListByClient($clientId)
	{
		$query = Cost::find()->where(['client_id' => $clientId]);
		$dataProvider = new ActiveDataProvider(['query' => $query]);

		return $this->render('index', ['dataProvider' => $dataProvider, 'clientId' => $clientId]);
	}

	/**
	 * @return string
	 */
	public function actionAllList()
	{
		$query = Cost::find()->joinWith(['client']);
		$dataProvider = new ActiveDataProvider(['query' => $query]);

		return $this->render('index', ['dataProvider' => $dataProvider, 'clientId' => false]);
	}

	/**
	 * @param $clientId
	 *
	 * @return string
	 * @throws \Exception
	 * @throws \yii\db\Exception
	 */
	public function actionCreate($clientId)
	{
		$cost = new Cost(['client_id' => $clientId]);
		if ($cost->load(Yii::$app->request->post()) && $cost->save() && BillingAction::changeCost($cost)) {
			$this->redirect(['cost/list-by-client', 'clientId' => $clientId]);
		}

		return $this->render('create', ['model' => $cost]);
	}

	/**
	 * @param $id
	 *
	 * @return string
	 * @throws \Exception
	 * @throws \yii\db\Exception
	 */
	public function actionUpdate($id)
	{
		$cost = $this->findModel($id);

		if ($cost->load(Yii::$app->request->post()) && $cost->save() && BillingAction::changeCost($cost)) {
			$this->redirect(['cost/list-by-client', 'clientId' => $cost->client_id]);
		}

		return $this->render('update', ['model' => $cost]);
	}

	/**
	 * @param $id
	 *
	 * @return bool
	 * @throws \Exception
	 * @throws \Throwable
	 * @throws \yii\db\StaleObjectException
	 */
	public function actionDelete($id)
	{
		$cost = $this->findModel($id);
		$clientId = $cost->client_id;
		if ($cost->delete()) {
			$this->redirect(['cost/list-by-client', 'clientId' => $clientId]);
		}

		return false;
	}

	/**
	 * @param $id
	 *
	 * @return array|Cost|null|\yii\db\ActiveRecord
	 */
	private function findModel($id)
	{
		if (!($model = Cost::find()->where(['id' => $id])->one())) {
			throw new NotFoundHttpException('Указанная страница не найдена.');
		}

		return $model;
	}

}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use common\models\User;
use yii\filters\AccessControl;
use yii\data\ActiveDataProvider;
use frontend\models\UserForm;
use Yii;
use yii\web\NotFoundHttpException;

class UserController extends \yii\web\Controller
{
	/**
	 * @return array
	 */
	public function behaviors()
	{
		return [
			'access' => [
				'class' => AccessControl::className(),
				'rules' => [
					[
						'actions' => ['create', 'delete', 'update', 'index', 'view'],
						'allow' => true,
						'roles' => ['@'],
					],
				],
			],
		];
	}

	/**
	 * @return string
	 */
    public function actionCreate()
    {
	    $model = new UserForm(null, ['scenario' => UserForm::SCENARIO_SIGNUP]);
	    if ($model->load(Yii::$app->request->post()) && $model->signup()) {
		    $this->redirect('/admin/user/index');
	    }

        return $this->render('create', ['model' => $model]);
    }

	/**
	 * @param $id
	 *
	 * @return bool
	 * @throws NotFoundHttpException
	 * @throws \Exception
	 * @throws \Throwable
	 * @throws \yii\db\StaleObjectException
	 */
    public function actionDelete($id)
    {
    	$model = $this->getUser($id);
    	if ($model->delete()) {
    		$this->redirect(['index']);
	    }

	    return false;
    }

	/**
	 * @return string
	 */
    public function actionIndex()
    {
	    $dataProvider = new ActiveDataProvider(['query' => User::find()->with('balance')]);

	    return $this->render('index', ['dataProvider' => $dataProvider]);
    }

	/**
	 * @param $id
	 *
	 * @return string
	 * @throws NotFoundHttpException
	 */
    public function actionUpdate($id)
    {
	    $user = $this->getUser($id);
	    $model = new UserForm($user, ['scenario' => UserForm::SCENARIO_ADMIN_EDIT]);
	    if ($model->load(Yii::$app->request->post()) && $model->update()) {
		    $this->redirect('/admin/user/index');
	    }

        return $this->render('update', ['model' => $model]);
    }

	/**
	 * @param $id
	 *
	 * @return User
	 * @throws NotFoundHttpException
	 */
	private function getUser($id)
	{
		if (!($user = User::find()->where(['id' => $id])->one())) {
			throw new NotFoundHttpException('Указанная страница не найдена.');
		}

		return $user;
    }
}

backend/views/cost/_form.php
<?
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use common\models\Bill;
use dosamigos\datepicker\DateRangePicker;

/*
 * @var $this yii\web\View
 * @var $form yii\bootstrap\ActiveForm
 * @var $model \common\models\Cost
 */

?>

<div class="row">
	<div class="col-lg-5">
		<? $form = ActiveForm::begin(['id' => 'cost-form']); ?>

		<?= $form->field($model, 'date_from')->widget(DateRangePicker::className(), [
				'attributeTo' => 'date_to',
				'form' => $form,
				'language' => 'ru',
				'size' => 'md',
				'clientOptions' => [
					'autoclose' => true,
					'format' => 'dd-mm-yyyy',
				],
			]
		) ?>

		<?= $form->field($model, 'sum'); ?>

		<div class="form-group">
			<?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary', 'name' => 'save-button']) ?>
		</div>

		<? ActiveForm::end(); ?>
	</div>
</div>

backend/views/cost/create.php
<?
use common\models\Cost;

/*
 * @var Cost $model
 */
?>

<h1>Добавление расхода</h1>

<?= $this->render('_form', ['model' => $model]); ?>

backend/views/cost/index.php
<?
use common\models\Cost;
use yii\grid\GridView;
use yii\helpers\Html;

/*
 * @var $this yii\web\View
 * @var $dataProvider ActiveDataProvider
 * @var integer $clientId
 */

$columns = ['id'];
if (!$clientId) {
	$columns[] = [
		'attribute' => 'Client',
		'format' => 'raw',
		'value'     => function (Cost $model) {
			return Html::a($model->client->username, ['user/update', 'id' => $model->client_id]);
		}
	];
}
$columns = array_merge(
	$columns,
	[
		[
			'attribute' => 'date_from',
			'format'    => ['date', 'php:d.m.Y']
		],
		[
			'attribute' => 'date_to',
			'format'    => ['date', 'php:d.m.Y']
		],
		'sum',
		[
			'class'         => 'yii\grid\ActionColumn',
			'headerOptions' => ['width' => '80'],
			'template'      => '{update} {delete}',
		]
	]
);
?>
<? if ($clientId): ?>
	<h1>Расходы клиента</h1>
	<p>
		<?= Html::a(Html::button('Создать', ['class' => 'btn btn-primary']), ['cost/create', 'clientId' => $clientId]); ?>
	</p>
<? else: ?>
	<h1>Расходы клиентов</h1>
<? endif; ?>

<?= GridView::widget(
	[
		'dataProvider' => $dataProvider,
		'columns'      => $columns
	]);
?>

backend/views/cost/update.php
<?
use common\models\Cost;

/*
 * @var Cost $model
 */

?>
<h1>Изменение расхода</h1>

<?= $this->render('_form', ['model' => $model]); ?>